/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesWritingSceneSpecsRouteImport } from './routes/guides/writing-scene-specs'
import { Route as GuidesWritingInlineAssertionsRouteImport } from './routes/guides/writing-inline-assertions'
import { Route as GuidesLlmPromptRouteImport } from './routes/guides/llm-prompt'

const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesWritingSceneSpecsRoute = GuidesWritingSceneSpecsRouteImport.update({
  id: '/guides/writing-scene-specs',
  path: '/guides/writing-scene-specs',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesWritingInlineAssertionsRoute =
  GuidesWritingInlineAssertionsRouteImport.update({
    id: '/guides/writing-inline-assertions',
    path: '/guides/writing-inline-assertions',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesLlmPromptRoute = GuidesLlmPromptRouteImport.update({
  id: '/guides/llm-prompt',
  path: '/guides/llm-prompt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/guides/llm-prompt': typeof GuidesLlmPromptRoute
  '/guides/writing-inline-assertions': typeof GuidesWritingInlineAssertionsRoute
  '/guides/writing-scene-specs': typeof GuidesWritingSceneSpecsRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/guides/llm-prompt': typeof GuidesLlmPromptRoute
  '/guides/writing-inline-assertions': typeof GuidesWritingInlineAssertionsRoute
  '/guides/writing-scene-specs': typeof GuidesWritingSceneSpecsRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/guides/llm-prompt': typeof GuidesLlmPromptRoute
  '/guides/writing-inline-assertions': typeof GuidesWritingInlineAssertionsRoute
  '/guides/writing-scene-specs': typeof GuidesWritingSceneSpecsRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/guides/llm-prompt'
    | '/guides/writing-inline-assertions'
    | '/guides/writing-scene-specs'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/guides/llm-prompt'
    | '/guides/writing-inline-assertions'
    | '/guides/writing-scene-specs'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/guides/llm-prompt'
    | '/guides/writing-inline-assertions'
    | '/guides/writing-scene-specs'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  GuidesLlmPromptRoute: typeof GuidesLlmPromptRoute
  GuidesWritingInlineAssertionsRoute: typeof GuidesWritingInlineAssertionsRoute
  GuidesWritingSceneSpecsRoute: typeof GuidesWritingSceneSpecsRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/writing-scene-specs': {
      id: '/guides/writing-scene-specs'
      path: '/guides/writing-scene-specs'
      fullPath: '/guides/writing-scene-specs'
      preLoaderRoute: typeof GuidesWritingSceneSpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/writing-inline-assertions': {
      id: '/guides/writing-inline-assertions'
      path: '/guides/writing-inline-assertions'
      fullPath: '/guides/writing-inline-assertions'
      preLoaderRoute: typeof GuidesWritingInlineAssertionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/llm-prompt': {
      id: '/guides/llm-prompt'
      path: '/guides/llm-prompt'
      fullPath: '/guides/llm-prompt'
      preLoaderRoute: typeof GuidesLlmPromptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  GuidesLlmPromptRoute: GuidesLlmPromptRoute,
  GuidesWritingInlineAssertionsRoute: GuidesWritingInlineAssertionsRoute,
  GuidesWritingSceneSpecsRoute: GuidesWritingSceneSpecsRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
