/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferenceIndexRouteImport } from './routes/reference/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as FaqIndexRouteImport } from './routes/faq/index'
import { Route as ReferencePageNameRouteImport } from './routes/reference/$pageName'
import { Route as GuidesPageNameRouteImport } from './routes/guides/$pageName'
import { Route as FaqPageNameRouteImport } from './routes/faq/$pageName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceIndexRoute = ReferenceIndexRouteImport.update({
  id: '/reference/',
  path: '/reference/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqIndexRoute = FaqIndexRouteImport.update({
  id: '/faq/',
  path: '/faq/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencePageNameRoute = ReferencePageNameRouteImport.update({
  id: '/reference/$pageName',
  path: '/reference/$pageName',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesPageNameRoute = GuidesPageNameRouteImport.update({
  id: '/guides/$pageName',
  path: '/guides/$pageName',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqPageNameRoute = FaqPageNameRouteImport.update({
  id: '/faq/$pageName',
  path: '/faq/$pageName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq/$pageName': typeof FaqPageNameRoute
  '/guides/$pageName': typeof GuidesPageNameRoute
  '/reference/$pageName': typeof ReferencePageNameRoute
  '/faq/': typeof FaqIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/reference/': typeof ReferenceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq/$pageName': typeof FaqPageNameRoute
  '/guides/$pageName': typeof GuidesPageNameRoute
  '/reference/$pageName': typeof ReferencePageNameRoute
  '/faq': typeof FaqIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/reference': typeof ReferenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq/$pageName': typeof FaqPageNameRoute
  '/guides/$pageName': typeof GuidesPageNameRoute
  '/reference/$pageName': typeof ReferencePageNameRoute
  '/faq/': typeof FaqIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/reference/': typeof ReferenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq/$pageName'
    | '/guides/$pageName'
    | '/reference/$pageName'
    | '/faq/'
    | '/guides/'
    | '/reference/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq/$pageName'
    | '/guides/$pageName'
    | '/reference/$pageName'
    | '/faq'
    | '/guides'
    | '/reference'
  id:
    | '__root__'
    | '/'
    | '/faq/$pageName'
    | '/guides/$pageName'
    | '/reference/$pageName'
    | '/faq/'
    | '/guides/'
    | '/reference/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqPageNameRoute: typeof FaqPageNameRoute
  GuidesPageNameRoute: typeof GuidesPageNameRoute
  ReferencePageNameRoute: typeof ReferencePageNameRoute
  FaqIndexRoute: typeof FaqIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ReferenceIndexRoute: typeof ReferenceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/': {
      id: '/reference/'
      path: '/reference'
      fullPath: '/reference/'
      preLoaderRoute: typeof ReferenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/': {
      id: '/faq/'
      path: '/faq'
      fullPath: '/faq/'
      preLoaderRoute: typeof FaqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/$pageName': {
      id: '/reference/$pageName'
      path: '/reference/$pageName'
      fullPath: '/reference/$pageName'
      preLoaderRoute: typeof ReferencePageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$pageName': {
      id: '/guides/$pageName'
      path: '/guides/$pageName'
      fullPath: '/guides/$pageName'
      preLoaderRoute: typeof GuidesPageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/$pageName': {
      id: '/faq/$pageName'
      path: '/faq/$pageName'
      fullPath: '/faq/$pageName'
      preLoaderRoute: typeof FaqPageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqPageNameRoute: FaqPageNameRoute,
  GuidesPageNameRoute: GuidesPageNameRoute,
  ReferencePageNameRoute: ReferencePageNameRoute,
  FaqIndexRoute: FaqIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ReferenceIndexRoute: ReferenceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
