#:schema node_modules/wrangler/config-schema.json
name = "scenetest-docs"
main = "./.output/server/index.mjs"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./.output/public"
binding = "ASSETS"
